/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  IsBoolean,
  ValidateNested,
} from "class-validator";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { UserConfigUpdateManyWithoutUserModelsInput } from "./UserConfigUpdateManyWithoutUserModelsInput";
import { Type } from "class-transformer";
import { UsersWorkspaceUpdateManyWithoutUserModelsInput } from "./UsersWorkspaceUpdateManyWithoutUserModelsInput";
import { UserVerificationCodeUpdateManyWithoutUserModelsInput } from "./UserVerificationCodeUpdateManyWithoutUserModelsInput";

@InputType()
class UserModelUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  status?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => UserConfigUpdateManyWithoutUserModelsInput,
  })
  @ValidateNested()
  @Type(() => UserConfigUpdateManyWithoutUserModelsInput)
  @IsOptional()
  @Field(() => UserConfigUpdateManyWithoutUserModelsInput, {
    nullable: true,
  })
  userConfigs?: UserConfigUpdateManyWithoutUserModelsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;

  @ApiProperty({
    required: false,
    type: () => UsersWorkspaceUpdateManyWithoutUserModelsInput,
  })
  @ValidateNested()
  @Type(() => UsersWorkspaceUpdateManyWithoutUserModelsInput)
  @IsOptional()
  @Field(() => UsersWorkspaceUpdateManyWithoutUserModelsInput, {
    nullable: true,
  })
  usersWorkspaces?: UsersWorkspaceUpdateManyWithoutUserModelsInput;

  @ApiProperty({
    required: false,
    type: () => UserVerificationCodeUpdateManyWithoutUserModelsInput,
  })
  @ValidateNested()
  @Type(() => UserVerificationCodeUpdateManyWithoutUserModelsInput)
  @IsOptional()
  @Field(() => UserVerificationCodeUpdateManyWithoutUserModelsInput, {
    nullable: true,
  })
  userVerificationCodes?: UserVerificationCodeUpdateManyWithoutUserModelsInput;
}

export { UserModelUpdateInput as UserModelUpdateInput };
